### ISSUE TITLE
Form styling needed if searchbar and if applying this style to gms

### ISSUE THREAD

**Issue by svbeon** [freenode/web-7.0#141]
Suggestion (dummycode):

``` css
input[type=text] .search:before {
  font-family: "font awesome";
  content: "\f002"; /* .fa .fa-search */
} 
input[type=text] .search {
 padding-left: "width of icon";
} 
```
